development:
  sessions:
    default:
      database: teeny_url
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      database: teeny_url
      username: action
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
